project:
  type: website
  output-dir: _site
  resources:
    - "organizers/**"
    - "CNAME"

website:
  title: "WOST Madrid 2027"
  navbar: false
  page-navigation: false

format:
  html:
    theme: cosmo
    css: assets/css/main.css
    toc: false